In [91]:
import numpy as np
import copy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [72]:
x = np.random.rand(8).reshape(-1, 4)
print(x)
print([np.linalg.norm(e) for e in x])

[[0.34612069 0.94707788 0.40998374 0.24815047]
 [0.98305287 0.73072186 0.24064769 0.00471835]]
[1.116432432795445, 1.248311237289451]


In [122]:
class KSON:
    def __init__(self, num_inputs, num_outputs, learning_rate=0.01, epochs=100):
        self.num_inputs = num_inputs
        self.num_outputs = num_outputs
        self.learning_rate = learning_rate
        self.epochs = epochs

        # init weights
        self.weight = np.random.rand(self.num_outputs, self.num_inputs)
        print(self.weight)

    def fit(self, X):
        for i in range(self.epochs):
            # print(f'Epoch {i+1}')
            for idx, x in enumerate(X):
                d = [np.linalg.norm(e) for e in x - self.weight]
                winner = np.argmin(d)
                self.weight[winner] += self.learning_rate * (x - self.weight[winner])
            # print(self.weight)

    def predict(self, X):
        pred = []
        for idx, x in enumerate(X):
            d = [np.linalg.norm(e) for e in x - self.weight]
            winner = np.argmin(d)
            pred.append(winner)
        return np.array(pred)

In [123]:
kson = KSON(4, 2)
X = np.random.rand(40).reshape(-1, 4)
df = pd.DataFrame(X)
print(df.head())
kson.fit(X)

[[0.25483244 0.5837602  0.25502418 0.58047428]
 [0.50269788 0.37694762 0.32751461 0.2654707 ]]
          0         1         2         3
0  0.348693  0.167923  0.415221  0.698901
1  0.722933  0.730884  0.898217  0.018018
2  0.952751  0.592193  0.808412  0.337178
3  0.498833  0.923265  0.148405  0.952739
4  0.723936  0.506136  0.051491  0.982006


In [125]:
df = pd.read_csv('breast-cancer-wisconsin-data_data.csv')
print(df.columns)
from itertools import permutations
p = permutations(df.columns[1:], 2)
df['diagnosis'].replace('M', 1, inplace=True)
df['diagnosis'].replace('B', 0, inplace=True)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')


In [126]:
X = df.iloc[:, 2:32]
y = df.iloc[:, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)
kson = KSON(30, 2, 100)
kson.fit(X_train)
pred = kson.predict(X_test)
print(pred)
print(y_test)
print(accuracy_score(y_test, pred))

[[0.3571395  0.43564804 0.89932443 0.49113466 0.02476634 0.16342738
  0.02335313 0.57136809 0.9443076  0.33540213 0.64780868 0.09341472
  0.26995609 0.65967653 0.11797002 0.54233801 0.68247445 0.81876859
  0.18682544 0.30934325 0.69424945 0.20171134 0.13960358 0.22070241
  0.49411576 0.94540406 0.97128631 0.01055044 0.38211778 0.0821316 ]
 [0.29247805 0.31472294 0.07851046 0.87422796 0.29366307 0.66237568
  0.06761967 0.41204833 0.99560494 0.61177179 0.32322542 0.80948527
  0.18545468 0.96270862 0.11451452 0.15597928 0.45722585 0.21936997
  0.64840245 0.07471538 0.50589863 0.4021637  0.19608313 0.93259356
  0.67861649 0.16376892 0.05184263 0.96512654 0.55692761 0.38901993]]


C:\Users\STUDENT\AppData\Local\Temp\ipykernel_1828\1395329354.py:18: RuntimeWarning: overflow encountered in multiply
  self.weight[winner] += self.learning_rate * (x - self.weight[winner])
C:\Users\STUDENT\AppData\Local\Temp\ipykernel_1828\1395329354.py:18: RuntimeWarning: invalid value encountered in add
  self.weight[winner] += self.learning_rate * (x - self.weight[winner])


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1
 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0
 1 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1
 0 0 0]
0.5789473684210527


In [45]:
class HopfieldNetwork:
    def __init__(self, num_inputs):
        self.num_inputs = num_inputs
        self.X = None
        self.weight = np.zeros((self.num_inputs, self.num_inputs))
        # print(self.weight)

    def fit(self, X):
        self.X = X
        # print(self.X)
        for pattern in X:
            self.weight += np.dot(pattern.reshape(-1, 1), pattern.reshape(1, -1))

        np.fill_diagonal(self.weight, 0)
        # print(self.weight)


    def predict(self, malformed):
        _malformed = copy.deepcopy(malformed)
        for i in range(5):
            print(f'Iteration {i+1}')
            fixed = np.dot(malformed, self.weight)
            fixed[fixed >= 0] = 1
            fixed[fixed < 0] = -1
            if np.array_equal(malformed, fixed):
                print("Found")
                print(f'Malformed: {_malformed}')
                print(f'Fixed: {fixed}')
                break

            malformed = fixed
            print(malformed)
            
hp = HopfieldNetwork(5)
X = np.array([
    [-1, -1, 1, -1, 1],
    [1, -1, 1, -1, 1],
    [-1, 1, -1, 1, -1],
    [1, 1 ,1, -1, -1]
], dtype='float32')
hp.fit(X)
hp.predict([-1, -1, -1, -1, 1])

Iteration 1
[ 1. -1.  1.  1.  1.]
Iteration 2
[ 1. -1.  1. -1.  1.]
Iteration 3
Found
Malformed: [-1, -1, -1, -1, 1]
Fixed: [ 1. -1.  1. -1.  1.]
